// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: suggestions.proto

package suggestions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealKind int32

const (
	MealKind_Snack     MealKind = 0
	MealKind_Breakfast MealKind = 1
	MealKind_Lunch     MealKind = 2
	MealKind_Dinner    MealKind = 3
	MealKind_Dessert   MealKind = 4
)

// Enum value maps for MealKind.
var (
	MealKind_name = map[int32]string{
		0: "Snack",
		1: "Breakfast",
		2: "Lunch",
		3: "Dinner",
		4: "Dessert",
	}
	MealKind_value = map[string]int32{
		"Snack":     0,
		"Breakfast": 1,
		"Lunch":     2,
		"Dinner":    3,
		"Dessert":   4,
	}
)

func (x MealKind) Enum() *MealKind {
	p := new(MealKind)
	*p = x
	return p
}

func (x MealKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MealKind) Descriptor() protoreflect.EnumDescriptor {
	return file_suggestions_proto_enumTypes[0].Descriptor()
}

func (MealKind) Type() protoreflect.EnumType {
	return &file_suggestions_proto_enumTypes[0]
}

func (x MealKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MealKind.Descriptor instead.
func (MealKind) EnumDescriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{0}
}

type MealFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     *string  `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kcal     *int32   `protobuf:"varint,3,opt,name=kcal,proto3,oneof" json:"kcal,omitempty"`
	Grams    *int32   `protobuf:"varint,2,opt,name=grams,proto3,oneof" json:"grams,omitempty"`
	ProteinG *float64 `protobuf:"fixed64,4,opt,name=protein_g,json=proteinG,proto3,oneof" json:"protein_g,omitempty"`
	CarbsG   *float64 `protobuf:"fixed64,5,opt,name=carbs_g,json=carbsG,proto3,oneof" json:"carbs_g,omitempty"`
	FatG     *float64 `protobuf:"fixed64,6,opt,name=fat_g,json=fatG,proto3,oneof" json:"fat_g,omitempty"`
}

func (x *MealFood) Reset() {
	*x = MealFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealFood) ProtoMessage() {}

func (x *MealFood) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealFood.ProtoReflect.Descriptor instead.
func (*MealFood) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{0}
}

func (x *MealFood) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MealFood) GetKcal() int32 {
	if x != nil && x.Kcal != nil {
		return *x.Kcal
	}
	return 0
}

func (x *MealFood) GetGrams() int32 {
	if x != nil && x.Grams != nil {
		return *x.Grams
	}
	return 0
}

func (x *MealFood) GetProteinG() float64 {
	if x != nil && x.ProteinG != nil {
		return *x.ProteinG
	}
	return 0
}

func (x *MealFood) GetCarbsG() float64 {
	if x != nil && x.CarbsG != nil {
		return *x.CarbsG
	}
	return 0
}

func (x *MealFood) GetFatG() float64 {
	if x != nil && x.FatG != nil {
		return *x.FatG
	}
	return 0
}

type MealSuggestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      *MealKind `protobuf:"varint,1,opt,name=kind,proto3,enum=MealKind,oneof" json:"kind,omitempty"`
	Name      *string   `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TotalKcal *float64  `protobuf:"fixed64,3,opt,name=total_kcal,json=totalKcal,proto3,oneof" json:"total_kcal,omitempty"`
	Foods     *MealFood `protobuf:"bytes,7,opt,name=foods,proto3,oneof" json:"foods,omitempty"`
}

func (x *MealSuggestion) Reset() {
	*x = MealSuggestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealSuggestion) ProtoMessage() {}

func (x *MealSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealSuggestion.ProtoReflect.Descriptor instead.
func (*MealSuggestion) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{1}
}

func (x *MealSuggestion) GetKind() MealKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return MealKind_Snack
}

func (x *MealSuggestion) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MealSuggestion) GetTotalKcal() float64 {
	if x != nil && x.TotalKcal != nil {
		return *x.TotalKcal
	}
	return 0
}

func (x *MealSuggestion) GetFoods() *MealFood {
	if x != nil {
		return x.Foods
	}
	return nil
}

type MealFilterParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *string `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Value *string `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *MealFilterParam) Reset() {
	*x = MealFilterParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealFilterParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealFilterParam) ProtoMessage() {}

func (x *MealFilterParam) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealFilterParam.ProtoReflect.Descriptor instead.
func (*MealFilterParam) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{2}
}

func (x *MealFilterParam) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *MealFilterParam) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type MealFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       *string            `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Function   *string            `protobuf:"bytes,2,opt,name=function,proto3,oneof" json:"function,omitempty"`
	Parameters []*MealFilterParam `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *MealFilter) Reset() {
	*x = MealFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MealFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealFilter) ProtoMessage() {}

func (x *MealFilter) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealFilter.ProtoReflect.Descriptor instead.
func (*MealFilter) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{3}
}

func (x *MealFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MealFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

func (x *MealFilter) GetParameters() []*MealFilterParam {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SuggestMealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    *MealKind     `protobuf:"varint,1,opt,name=kind,proto3,enum=MealKind,oneof" json:"kind,omitempty"`
	Filters []*MealFilter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *SuggestMealRequest) Reset() {
	*x = SuggestMealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestMealRequest) ProtoMessage() {}

func (x *SuggestMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestMealRequest.ProtoReflect.Descriptor instead.
func (*SuggestMealRequest) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestMealRequest) GetKind() MealKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return MealKind_Snack
}

func (x *SuggestMealRequest) GetFilters() []*MealFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SuggestMealResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO: Yes this is bad and pedestrian, but sue me.
	Error       *string           `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Suggestions []*MealSuggestion `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
}

func (x *SuggestMealResponse) Reset() {
	*x = SuggestMealResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestMealResponse) ProtoMessage() {}

func (x *SuggestMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestMealResponse.ProtoReflect.Descriptor instead.
func (*SuggestMealResponse) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{5}
}

func (x *SuggestMealResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *SuggestMealResponse) GetSuggestions() []*MealSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type GetMealFiltersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMealFiltersRequest) Reset() {
	*x = GetMealFiltersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMealFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealFiltersRequest) ProtoMessage() {}

func (x *GetMealFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealFiltersRequest.ProtoReflect.Descriptor instead.
func (*GetMealFiltersRequest) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{6}
}

type GetMealFiltersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO: Yes this is bad and pedestrian, but sue me.
	Error   *string       `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Filters []*MealFilter `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *GetMealFiltersResponse) Reset() {
	*x = GetMealFiltersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suggestions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMealFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealFiltersResponse) ProtoMessage() {}

func (x *GetMealFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealFiltersResponse.ProtoReflect.Descriptor instead.
func (*GetMealFiltersResponse) Descriptor() ([]byte, []int) {
	return file_suggestions_proto_rawDescGZIP(), []int{7}
}

func (x *GetMealFiltersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetMealFiltersResponse) GetFilters() []*MealFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

var File_suggestions_proto protoreflect.FileDescriptor

var file_suggestions_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x6f, 0x6f, 0x64,
	0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6b, 0x63, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x04, 0x6b, 0x63, 0x61, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x02, 0x52, 0x05, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x5f, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x03, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x47, 0x88, 0x01, 0x01, 0x12,
	0x1c, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x62, 0x73, 0x5f, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x04, 0x52, 0x06, 0x63, 0x61, 0x72, 0x62, 0x73, 0x47, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a,
	0x05, 0x66, 0x61, 0x74, 0x5f, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x05, 0x52, 0x04,
	0x66, 0x61, 0x74, 0x47, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x63, 0x61, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x67, 0x72,
	0x61, 0x6d, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x5f,
	0x67, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x61, 0x72, 0x62, 0x73, 0x5f, 0x67, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x66, 0x61, 0x74, 0x5f, 0x67, 0x22, 0xc2, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x61, 0x6c,
	0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x4b,
	0x69, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x6b, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x09, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4b, 0x63, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x05, 0x66,
	0x6f, 0x6f, 0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x61,
	0x6c, 0x46, 0x6f, 0x6f, 0x64, 0x48, 0x03, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6b, 0x63,
	0x61, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x58, 0x0a, 0x0f,
	0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x61, 0x6c, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x30, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x68, 0x0a, 0x12, 0x53, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x4d, 0x65,
	0x61, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x25, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e,
	0x64, 0x22, 0x6d, 0x0a, 0x13, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x0b, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x73, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x25,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a,
	0x48, 0x0a, 0x08, 0x4d, 0x65, 0x61, 0x6c, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x6e, 0x61, 0x63, 0x6b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x72, 0x65, 0x61, 0x6b, 0x66,
	0x61, 0x73, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x75, 0x6e, 0x63, 0x68, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x65, 0x73, 0x73, 0x65, 0x72, 0x74, 0x10, 0x04, 0x32, 0x8c, 0x01, 0x0a, 0x0d, 0x4d, 0x65,
	0x61, 0x6c, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x12, 0x13, 0x2e, 0x53, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61,
	0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_suggestions_proto_rawDescOnce sync.Once
	file_suggestions_proto_rawDescData = file_suggestions_proto_rawDesc
)

func file_suggestions_proto_rawDescGZIP() []byte {
	file_suggestions_proto_rawDescOnce.Do(func() {
		file_suggestions_proto_rawDescData = protoimpl.X.CompressGZIP(file_suggestions_proto_rawDescData)
	})
	return file_suggestions_proto_rawDescData
}

var file_suggestions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_suggestions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_suggestions_proto_goTypes = []interface{}{
	(MealKind)(0),                  // 0: MealKind
	(*MealFood)(nil),               // 1: MealFood
	(*MealSuggestion)(nil),         // 2: MealSuggestion
	(*MealFilterParam)(nil),        // 3: MealFilterParam
	(*MealFilter)(nil),             // 4: MealFilter
	(*SuggestMealRequest)(nil),     // 5: SuggestMealRequest
	(*SuggestMealResponse)(nil),    // 6: SuggestMealResponse
	(*GetMealFiltersRequest)(nil),  // 7: GetMealFiltersRequest
	(*GetMealFiltersResponse)(nil), // 8: GetMealFiltersResponse
}
var file_suggestions_proto_depIdxs = []int32{
	0, // 0: MealSuggestion.kind:type_name -> MealKind
	1, // 1: MealSuggestion.foods:type_name -> MealFood
	3, // 2: MealFilter.parameters:type_name -> MealFilterParam
	0, // 3: SuggestMealRequest.kind:type_name -> MealKind
	4, // 4: SuggestMealRequest.filters:type_name -> MealFilter
	2, // 5: SuggestMealResponse.suggestions:type_name -> MealSuggestion
	4, // 6: GetMealFiltersResponse.filters:type_name -> MealFilter
	5, // 7: MealSuggester.SuggestMeal:input_type -> SuggestMealRequest
	7, // 8: MealSuggester.GetMealFilters:input_type -> GetMealFiltersRequest
	6, // 9: MealSuggester.SuggestMeal:output_type -> SuggestMealResponse
	8, // 10: MealSuggester.GetMealFilters:output_type -> GetMealFiltersResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_suggestions_proto_init() }
func file_suggestions_proto_init() {
	if File_suggestions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_suggestions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MealFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MealSuggestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MealFilterParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MealFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestMealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestMealResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMealFiltersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suggestions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMealFiltersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_suggestions_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_suggestions_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_suggestions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_suggestions_proto_goTypes,
		DependencyIndexes: file_suggestions_proto_depIdxs,
		EnumInfos:         file_suggestions_proto_enumTypes,
		MessageInfos:      file_suggestions_proto_msgTypes,
	}.Build()
	File_suggestions_proto = out.File
	file_suggestions_proto_rawDesc = nil
	file_suggestions_proto_goTypes = nil
	file_suggestions_proto_depIdxs = nil
}
